[build]
  publish = "."

# Regula principală pentru formularul Wellness
[[redirects]]
  from = "/wellness"
  to = "/wellness/index.html"
  status = 200

# Regula pentru pagina de succes din folderul wellness
[[redirects]]
  from = "/wellness/success"
  to = "/wellness/success.html"
  status = 200

# Regula pentru Acord (existentă)
[[redirects]]
  from = "/acord"
  to = "/acord_RO.html"
  status = 200